### PR TITLE
Fix qa app and ngrok debugging

### PR DESCRIPTION
**Pull request by scruff311**
This PR should have been opened and merged in before https://github.com/starburstlabs/crm-turbolinks-ios/pull/110 got merged in. We use the new Wealthbox framework which conditionally adds an `ngrok` header to requests to an `ngrok` domain. We also allow the webview to be debugged in everything but the production app.

### QA Steps
We already tested the ability to inspect the webview of the QA app build in https://github.com/starburstlabs/crm-turbolinks-ios/pull/110, but we did not test that you are still unable to inspect the webview in the production app.

- Download the regular production Wealthbox app from TestFlight (not the QA app) version 2.7.17
- Ensure you've enabled the Web Inspector in your phone settings (Settings > Safari > Advanced)
image

- Connect your phone to your computer using a cable
- Launch the production iOS app on your phone and log in
- Open Safari on your mac and open the [Develop](https://support.apple.com/lt-lt/guide/safari/sfri20948/17.0/mac/14.0) menu
- [ ] Confirm that you do not see the webview of the production app as an inspectable item

### CODE REVIEW

**Comment by tronmcp** [comment]
@scruff311 Can you include steps for QA that can demonstrate the PROD vs non-PROD functionality to confirm if PROD is inspectable or not?

**Comment by scruff311** [comment]
> @scruff311 Can you include steps for QA that can demonstrate the PROD vs non-PROD functionality to confirm if PROD is inspectable or not?

So this was already QAed in https://github.com/starburstlabs/crm-turbolinks-ios/pull/110, i just forgot to get it merged in before merging the parent iOS app PR (this project is a submodule of the iOS project, which itself is a submodule of the `wealthbox-mobile` project).

**Comment by tronmcp** [comment]
> > @scruff311 Can you include steps for QA that can demonstrate the PROD vs non-PROD functionality to confirm if PROD is inspectable or not?
> 
> So this was already QAed in [starburstlabs/crm-turbolinks-ios#110](https://github.com/starburstlabs/crm-turbolinks-ios/pull/110), i just forgot to get it merged in before merging the parent iOS app PR (this project is a submodule of the iOS project, which itself is a submodule of the `wealthbox-mobile` project).

@scruff311 Ok, my thought was we tested the debug in the previous PR but we didn't test the opposite when running the production app confirming you can't debug. I assume this is a use case. Maybe I'm missing something. Let me know.

**Comment by scruff311** [comment]
> > > @scruff311 Can you include steps for QA that can demonstrate the PROD vs non-PROD functionality to confirm if PROD is inspectable or not?
> > 
> > 
> > So this was already QAed in [starburstlabs/crm-turbolinks-ios#110](https://github.com/starburstlabs/crm-turbolinks-ios/pull/110), i just forgot to get it merged in before merging the parent iOS app PR (this project is a submodule of the iOS project, which itself is a submodule of the `wealthbox-mobile` project).
> 
> @scruff311 Ok, my thought was we tested the debug in the previous PR but we didn't test the opposite when running the production app confirming you can't debug. I assume this is a use case. Maybe I'm missing something. Let me know.

Oh gotcha. Good point. I've added steps for testing that we still _cannot_ inspect the web view of the prod app.

UPDATE: Only apps downloaded from the App Store are considered true 'production' apps, so a TestFlight build will still allow the webview to be inspected on the prod app downloaded through TestFlight.

**Review by mike-leone-wealthbox — APPROVED** [review]
looks good!

**Pull request merged**
